# используем язык java. Travis CI поддерживает другие языки тоже.
language: java

jdk:
  - openjdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false

services:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE tracker_test;" -U postgres
  - psql -c "CREATE USER tester WITH PASSWORD 'password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE tracker_test TO tester;" -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo.
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала.
notifications:
  email:
    recipients:
      - 1kbkbkbkb1@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
